export SHELL:=/bin/bash
export MAKEFLAGS+=--no-print-directory
export DEBUG:=false
export VENDOR:=codemity
export GOPRIVATE:=github.com/${VENDOR}
export BASE_NAME:=$(shell basename ${PWD})
export IMAGE_NAME:=${VENDOR}/${BASE_NAME}
export MINIMUM_COVERAGE:=0
