docs:
	@notatio coi --command="${BASE_NAME} toc --document=README.md --header='Table of contents' int --help" --document=README.md --header='`int`' --limiter-left=### --limiter-right="### " --index=1
	@notatio coi --command="${BASE_NAME} toc --document=README.md --header='Table of contents' ext --help" --document=README.md --header='`ext`' --limiter-left=### --limiter-right="## " --index=1
