name: Check

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check
        run: make cmd COMMAND="make check"
